[package]
org = "ballerinax"
name = "taskcode_0001"
version = "1.0.0"
distribution = "2201.9.0"
authors = ["Ballerina"]
keywords = ["Business Management/ERP", "Cost/Paid", "Vendor/SAP", "Production Planning", "PP"]
repository = "https://github.com/ballerina-platform/module-ballerinax-sap.s4hana.qm"
icon = "../icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
